#Twilio
TWILIO_ACCOUNT_SID ='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWILIO_AUTH_TOKEN ='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
FROM_PHONE_NUMBER ='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' 
TO_PHONE_NUMBER = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
FROM_PHONE_NUMBER_TEXT = 'XXXXXXXXXXXXX'
TO_PHONE_NUMBER_TEXT = 'XXXXXXXXXXXXXX'

#Banxico
APIBANX_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXS'

